Repository cakephp/phinx, pull requests merged in 2018-03, with the labels that each got.

#1232 remove duplicate version string from list command
  src/Phinx/Console/PhinxApplication.php
  tests/Phinx/Console/Command/ListTest.php
Labels: bug, needs tests

#1294 Allow signed named primary_key
  src/Phinx/Db/Adapter/MysqlAdapter.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Labels: enhancement

#1282 Move from PHP 5.4 to PHP 7.0 for Docker
  Dockerfile
Labels: enhancement

#1215 Simplify getSqlType types with default name
  src/Phinx/Db/Adapter/MysqlAdapter.php
  src/Phinx/Db/Adapter/PostgresAdapter.php
  src/Phinx/Db/Adapter/SQLiteAdapter.php
  src/Phinx/Db/Adapter/SqlServerAdapter.php
Labels: enhancement

#1248 Fix MySQL BIT Column Type (#1106)
  src/Phinx/Db/Adapter/AdapterInterface.php
  src/Phinx/Db/Adapter/MysqlAdapter.php
  src/Phinx/Db/Adapter/PdoAdapter.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Labels: enhancement, mysql
