Repository cakephp/phinx, pull requests merged in 2018-04, with the labels that each got.

#1272 Add JSON support to SQLite adapter
  src/Phinx/Db/Adapter/SQLiteAdapter.php
  tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Labels: enhancement

#1325 Fix status command exit code
  src/Phinx/Migration/Manager.php
Labels: enhancement, waiting on feedback

#1318 Add --fake flag to migrate and rollback commands
  src/Phinx/Console/Command/Migrate.php
  src/Phinx/Console/Command/Rollback.php
  src/Phinx/Console/PhinxApplication.php
  src/Phinx/Migration/Manager.php
  src/Phinx/Migration/Manager/Environment.php
  tests/Phinx/Console/Command/MigrateTest.php
  tests/Phinx/Console/Command/RollbackTest.php
Labels: feature

#1322 Improve error reporting when loading migration file
  src/Phinx/Migration/Manager.php
Labels: enhancement

#1313 Fix SQLite transaction handling
  src/Phinx/Db/Adapter/SQLiteAdapter.php
  tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Labels: bug

#1175 Add custom column support
  .travis.yml
  docs/migrations.rst
  src/Phinx/Db/Adapter/AbstractAdapter.php
  src/Phinx/Db/Adapter/MysqlAdapter.php
  src/Phinx/Db/Adapter/PdoAdapter.php
  src/Phinx/Db/Adapter/PostgresAdapter.php
  src/Phinx/Db/Adapter/SQLiteAdapter.php
  src/Phinx/Db/Adapter/SqlServerAdapter.php
  src/Phinx/Db/Table.php
  src/Phinx/Db/Table/Column.php
  src/Phinx/Migration/Migration.template.php.dist
  src/Phinx/Util/Literal.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
  tests/Phinx/Db/Adapter/PostgresAdapterTest.php
  tests/Phinx/Util/LiteralTest.php
Labels: enhancement

#1298 Fix SQLite & MySQL identity definition incompatibility
  src/Phinx/Db/Adapter/SQLiteAdapter.php
  tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Labels: bug

#1296 Fix SQLite identity nullability
  src/Phinx/Db/Adapter/SQLiteAdapter.php
  tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Labels: bug

#1330 Add Support for Database-Agnostic DSN
  docs/configuration.rst
  src/Phinx/Migration/Manager/Environment.php
  tests/Phinx/Migration/Manager/EnvironmentTest.php
Labels: feature

#1270 Adds dry run support for PDO inserts and bulkinserts
  src/Phinx/Db/Adapter/PdoAdapter.php
  src/Phinx/Db/Adapter/SQLiteAdapter.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
  tests/Phinx/Db/Adapter/PostgresAdapterTest.php
  tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Labels: bug, waiting on feedback

#1235 Quote Table Name - fix issue #575
  src/Phinx/Db/Adapter/PdoAdapter.php
Labels: bug, needs tests

#1222 refs #649 ignore limit in bool columns and cast to bool defaults for postgres
  src/Phinx/Db/Adapter/PostgresAdapter.php
  tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Labels: enhancement, postgres

#1323 Add ability to specify limit for timestamp/date/time columns for mysql
  docker-compose.yml
  src/Phinx/Db/Adapter/MysqlAdapter.php
  src/Phinx/Db/Adapter/PdoAdapter.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
  tests/Phinx/Db/Adapter/MysqlAdapterUnitTest.php
Labels: waiting on feedback

#968 Document supported table options
  docs/migrations.rst
Labels: docs, waiting on feedback

#1039 Precision for PostgreSQL time types
  src/Phinx/Db/Adapter/PostgresAdapter.php
  tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Labels: enhancement, postgres

#1280 Use phpstan v9 and fix reported errors.
  .travis.yml
  phpstan.neon
  src/Phinx/Console/Command/AbstractCommand.php
  src/Phinx/Db/Adapter/PostgresAdapter.php
  src/Phinx/Db/Adapter/ProxyAdapter.php
  src/Phinx/Db/Adapter/SqlServerAdapter.php
  src/Phinx/Db/Table.php
  src/Phinx/Db/Table/Column.php
  src/Phinx/Migration/Manager.php
Labels: enhancement
