Repository cakephp/phinx, pull requests merged in 2019-12, with the labels that each got.

#1639 postgresql does not allow limit parameter for type text
  src/Phinx/Db/Adapter/PostgresAdapter.php
Labels: bug

#1633 Fix using unsigned with smallint for mysql
  src/Phinx/Db/Adapter/MysqlAdapter.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Labels: bug

#1629 Add block on executing Phinx inside another symfony console app
  docs/commands.rst
Labels: docs

#1659 Add save() call after removeIndex in docs
  docs/migrations.rst
Labels: docs

#1658 Update travis to test against 7.4 stable
  .travis.yml
Labels: enhancement

#1667 Fix offset warning shown when using invalid version for breakpoint
  src/Phinx/Migration/Manager.php
  tests/Phinx/Migration/ManagerTest.php
Labels: bug

#1670 Standardize exit codes to class constants
  src/Phinx/Console/Command/AbstractCommand.php
  src/Phinx/Console/Command/Breakpoint.php
  src/Phinx/Console/Command/Create.php
  src/Phinx/Console/Command/Init.php
  src/Phinx/Console/Command/ListAliases.php
  src/Phinx/Console/Command/Migrate.php
  src/Phinx/Console/Command/Rollback.php
  src/Phinx/Console/Command/SeedCreate.php
  src/Phinx/Console/Command/SeedRun.php
  src/Phinx/Console/Command/Status.php
  src/Phinx/Console/Command/Test.php
  src/Phinx/Migration/Manager.php
  tests/Phinx/Console/Command/BreakpointTest.php
  tests/Phinx/Console/Command/MigrateTest.php
  tests/Phinx/Console/Command/RollbackTest.php
  tests/Phinx/Console/Command/SeedRunTest.php
  tests/Phinx/Console/Command/StatusTest.php
  tests/Phinx/Migration/ManagerTest.php
Labels: enhancement

#1627 Add fetch_mode option support for PDO adapters
  src/Phinx/Db/Adapter/MysqlAdapter.php
  src/Phinx/Db/Adapter/PdoAdapter.php
  src/Phinx/Db/Adapter/PostgresAdapter.php
  src/Phinx/Db/Adapter/SQLiteAdapter.php
  src/Phinx/Db/Adapter/SqlServerAdapter.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
  tests/Phinx/Db/Adapter/PostgresAdapterTest.php
  tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
  tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
Labels: enhancement

#1669 Print version order when running migrate
  src/Phinx/Console/Command/Migrate.php
  src/Phinx/Console/Command/Rollback.php
  tests/Phinx/Console/Command/MigrateTest.php
Labels: enhancement

#1675 Allow setting SRID for geometry types
  src/Phinx/Db/Adapter/PostgresAdapter.php
  src/Phinx/Db/Table/Column.php
Labels: enhancement
