Repository cakephp/phinx, pull requests merged in 2019-08, with the labels that each got.

#1588 Fixed Command names
  src/Phinx/Console/Command/Breakpoint.php
  src/Phinx/Console/Command/Create.php
  src/Phinx/Console/Command/Init.php
  src/Phinx/Console/Command/Migrate.php
  src/Phinx/Console/Command/Rollback.php
  src/Phinx/Console/Command/SeedCreate.php
  src/Phinx/Console/Command/SeedRun.php
  src/Phinx/Console/Command/Status.php
  src/Phinx/Console/Command/Test.php
  src/Phinx/Console/PhinxApplication.php
  tests/Phinx/Console/Command/BreakpointTest.php
  tests/Phinx/Console/Command/CreateTest.php
  tests/Phinx/Console/Command/InitTest.php
  tests/Phinx/Console/Command/MigrateTest.php
  tests/Phinx/Console/Command/RollbackTest.php
  tests/Phinx/Console/Command/SeedCreateTest.php
  tests/Phinx/Console/Command/SeedRunTest.php
  tests/Phinx/Console/Command/StatusTest.php
Labels: bug

#1591 Update phpunit/phpunit requirement from >=5.7,<7.0 to >=5.7,<8.0
  composer.json
  phpunit.xml.dist
  tests/Phinx/Migration/AbstractMigrationTest.php
Labels: enhancement

#1596 Use existing protected static defaultName for console commands
  composer.json
  src/Phinx/Console/Command/Breakpoint.php
  src/Phinx/Console/Command/Create.php
  src/Phinx/Console/Command/Init.php
  src/Phinx/Console/Command/Migrate.php
  src/Phinx/Console/Command/Rollback.php
  src/Phinx/Console/Command/SeedCreate.php
  src/Phinx/Console/Command/SeedRun.php
  src/Phinx/Console/Command/Status.php
  src/Phinx/Console/Command/Test.php
  src/Phinx/Console/PhinxApplication.php
  tests/Phinx/Console/Command/BreakpointTest.php
  tests/Phinx/Console/Command/CreateTest.php
  tests/Phinx/Console/Command/InitTest.php
  tests/Phinx/Console/Command/MigrateTest.php
  tests/Phinx/Console/Command/RollbackTest.php
  tests/Phinx/Console/Command/SeedCreateTest.php
  tests/Phinx/Console/Command/SeedRunTest.php
  tests/Phinx/Console/Command/StatusTest.php
Labels: enhancement

#1592 add --prefer-lowest flag to composer install for travis-ci
  .travis.yml
  composer.json
Labels: dependencies, testing

#1606 Fix ordering of arguments to implode
  src/Phinx/Util/Util.php
Labels: enhancement

#1605 Fix PHP7.4
  .travis.yml
  src/Phinx/Migration/Manager.php
Labels: bug
