Repository cakephp/phinx, pull requests merged in 2020-04, with the labels that each got.

#1320 Adds Custom Data Types (Data Domain)
  docs/en/migrations.rst
  src/Phinx/Config/Config.php
  src/Phinx/Config/ConfigInterface.php
  src/Phinx/Db/Adapter/AbstractAdapter.php
  src/Phinx/Db/Adapter/AdapterInterface.php
  src/Phinx/Db/Adapter/AdapterWrapper.php
  src/Phinx/Migration/Manager.php
  tests/Phinx/Config/AbstractConfigTest.php
  tests/Phinx/Config/ConfigTest.php
  tests/Phinx/Db/Adapter/DataDomainTest.php
  tests/Phinx/Db/Adapter/TablePrefixAdapterTest.php
  tests/Phinx/Migration/ManagerTest.php
Labels: feature

#1624 Add schema-support to MysqlAdapter
  src/Phinx/Db/Adapter/MysqlAdapter.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Labels: enhancement

#1734 Start adding binaryuuid support.
  src/Phinx/Db/Adapter/AdapterInterface.php
  src/Phinx/Db/Adapter/MysqlAdapter.php
  src/Phinx/Db/Adapter/PostgresAdapter.php
  src/Phinx/Db/Adapter/SQLiteAdapter.php
  src/Phinx/Db/Table/Column.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
  tests/Phinx/Db/Adapter/PostgresAdapterTest.php
  tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Labels: feature

#1512 Add support to configure custom seeder base class
  docs/en/configuration.rst
  src/Phinx/Config/Config.php
  src/Phinx/Config/ConfigInterface.php
  src/Phinx/Console/Command/SeedCreate.php
Labels: feature

#1744 Relax migration & seed class name restrictions
  src/Phinx/Util/Util.php
  tests/Phinx/Util/UtilTest.php
Labels: bug

#1755 Add support for tinyint. Fix bool issue.
  src/Phinx/Db/Adapter/AdapterInterface.php
  src/Phinx/Db/Adapter/AdapterWrapper.php
  src/Phinx/Db/Adapter/MysqlAdapter.php
  src/Phinx/Db/Adapter/PdoAdapter.php
  src/Phinx/Db/Adapter/PostgresAdapter.php
  src/Phinx/Db/Adapter/ProxyAdapter.php
  src/Phinx/Db/Adapter/SQLiteAdapter.php
  src/Phinx/Db/Adapter/SqlServerAdapter.php
  src/Phinx/Db/Adapter/TablePrefixAdapter.php
  src/Phinx/Db/Adapter/TimedOutputAdapter.php
  src/Phinx/Db/Table/Column.php
  tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Labels: enhancement
