Repository cakephp/phinx, pull requests merged in 2020-07, with the labels that each got.

#1835 Replace hard-coded phinx db name with MYSQL_DB_CONFIG['name']
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Labels: testing

#1830 Add support for native Mysql blob types and fallback for binary
  docs/en/migrations.rst
  src/Phinx/Db/Adapter/AdapterInterface.php
  src/Phinx/Db/Adapter/MysqlAdapter.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Labels: enhancement

#1834 Updated travis config to only run code coverage
  .travis.yml
Labels: testing

#1845 Fix adding columns to existing sqlite table with table constraints
  src/Phinx/Db/Adapter/SQLiteAdapter.php
  tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Labels: bug

#1846 Remove chat badge
  README.md
Labels: docs
