Repository cakephp/phinx, pull requests merged in 2020-10, with the labels that each got.

#1888 Index column sort order #1661
  src/Phinx/Db/Adapter/MysqlAdapter.php
  src/Phinx/Db/Adapter/PostgresAdapter.php
  src/Phinx/Db/Adapter/SqlServerAdapter.php
  src/Phinx/Db/Table/Index.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
  tests/Phinx/Db/Adapter/PostgresAdapterTest.php
  tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
Labels: bug

#1910 Add MySQL FIRST support.
  docs/en/migrations.rst
  src/Phinx/Db/Adapter/MysqlAdapter.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Labels: hacktoberfest-accepted

#1908 Add support for include clause when adding an index #1903
  src/Phinx/Db/Adapter/PostgresAdapter.php
  src/Phinx/Db/Adapter/SqlServerAdapter.php
  src/Phinx/Db/Table/Index.php
  tests/Phinx/Db/Adapter/PostgresAdapterTest.php
  tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
Labels: enhancement

#1904 add ability to set generic PDO attributes
  docs/en/configuration.rst
  src/Phinx/Db/Adapter/MysqlAdapter.php
  src/Phinx/Db/Adapter/PdoAdapter.php
  src/Phinx/Db/Adapter/SqlServerAdapter.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
  tests/Phinx/Db/Adapter/PdoAdapterTest.php
  tests/Phinx/Db/Adapter/PostgresAdapterTest.php
  tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
  tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
Labels: enhancement

#1899 make default PKs for mysql unsigned by default
  docs/en/migrations.rst
  src/Phinx/Db/Adapter/MysqlAdapter.php
  tests/Phinx/Db/Adapter/MysqlAdapterTest.php
  tests/Phinx/Migration/_files/drop_column_fk_index_regression/20190928205056_first_fk_index_migration.php
  tests/Phinx/Migration/_files/drop_index_regression/20121213232502_create_drop_fk_initial_schema.php
  tests/Phinx/Migration/_files/drop_table_with_fk_regression/20190928205060_second_drop_fk_migration.php
  tests/Phinx/Migration/_files/reversiblemigrations/20121224200852_create_user_logins_table.php
  tests/Phinx/Migration/_files/reversiblemigrations/20190928220334_add_column_index_fk.php
  tests/Phinx/Migration/_files_baz/reversiblemigrations/20151224200852_create_user_logins_table.php
  tests/Phinx/Migration/_files_foo_bar/reversiblemigrations/20161224200852_create_user_logins_table.php
Labels: enhancement
